### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by viharm** [matt1/CLIMediaRenderer#1]
I am trying to run this on Ubuntu Desktop 10.04 with openjdk-6-jre.

I get the following error when I try to launch the program with the command `java -jar  cliMediaRenderer.jar`

```
Exception in thread "main" java.lang.NullPointerException
        at java.io.File.<init>(File.java:239)
        at org.matt1.climediarenderer.services.CliMediaRenderer.loadIcon(CliMediaRenderer.java:119)
        at org.matt1.climediarenderer.services.CliMediaRenderer.<init>(CliMediaRenderer.java:197)
        at org.matt1.climediarenderer.services.CliMediaRenderer.<init>(CliMediaRenderer.java:111)
        at org.matt1.climediarenderer.MediaRenderer.main(MediaRenderer.java:23)
```

I have also tried to run the same command as a superuser, but get the same error.

**Comment by matt1** [comment]
Looks like this is a case of a missing properties file cliMediaRenderer.properties needs to be in the same directory as the jar.  There is a sample porperties file in the source

I've fixed the code to display a more sensible error message now.
